### ISSUE TITLE
Option to specify pixel format

### ISSUE THREAD

**Issue by timeinpixels** [edubart/sokol_gp#10]
Would it be possible to add the option to specify the pixel format for the pass?
I work with EDR/HDR and need non-default pixel formats.

I would need to somehow pass a new value to `pip_desc.colors[0].pixel_format` in `_sgp_make_pipeline`.

**Comment by edubart** [comment]
This feature was added in https://github.com/edubart/sokol_gp/commit/d89d15a110fd3d1a5f4e0820a0b1abc4d30be074
