### ISSUE TITLE
Is sokol_gp supposed to work with multiple sokol_gfx contexts?

### ISSUE THREAD

**Issue by larpon** [edubart/sokol_gp#14]
I've been try to get `sokol_gp` to work with multiple [`sokol_gfx` contexts](https://github.com/floooh/sokol/blob/master/sokol_gfx.h#L542-L583) I've tried to patch the code a bit here and there (just simple things, like removing the init_cookie check) - but I can't really get it to work properly. Do you think it could be possible to make it work somehow?

**Comment by Larpon** [comment]
**Small update**

I got it working to an extend where it renders, seemingly, fine, by simply [commenting out the init_cookie check](https://github.com/edubart/sokol_gp/blob/615364ba5084a4dd18ce18ad8573277b5b8d55c5/sokol_gp.h#L1086):
![image](https://user-images.githubusercontent.com/768942/189484701-b231344b-cb98-47ee-baf8-c7398757c5dc.png)

But when shutting the system I get a few errors from sokol:
```
_sg_uninit_pipeline: active context mismatch (must be same as for creation)
_sg_uninit_pipeline: active context mismatch (must be same as for creation)
_sg_uninit_pipeline: active context mismatch (must be same as for creation)
_sg_uninit_pipeline: active context mismatch (must be same as for creation)
_sg_uninit_pipeline: active context mismatch (must be same as for creation)
_sg_uninit_pipeline: active context mismatch (must be same as for creation)
_sg_uninit_pipeline: active context mismatch (must be same as for creation)
_sg_uninit_shader: active context mismatch (must be same as for creation)
_sg_uninit_buffer: active context mismatch (must be same as for creation)
_sg_uninit_image: active context mismatch (must be same as for creation)
```
