### ISSUE TITLE
use of undeclared identifier 'SG_SAMPLERTYPE_SAMPLE'

### ISSUE THREAD

**Issue by mumin16** [edubart/sokol_gp#25]
use of undeclared identifier 'SG_SAMPLERTYPE_SAMPLE'

**Comment by edubart** [comment]
Sokol GP was updated to use latest Sokol, which includes the samplers breaking change. Looks like you are using old Sokol, if you need to stick with it, you could use the Sokol GP from pre-samplers tag at `https://github.com/edubart/sokol_gp/releases/tag/pre-samplers` , but note that it is not being maintained anymore.

**Comment by edubart** [comment]
I just noticed Sokol released WebGPU with some new breaking changes, including a rename of this enum, I will take a look on this later. Meanwhile stick with a Sokol without WebGPU.

**Comment by edubart** [comment]
This was fixed in latest commits.
