### ISSUE TITLE
Ability to not clear the display?

### ISSUE THREAD

**Issue by kkukshtel** [edubart/sokol_gp#28]
I'm trying to figure out why _not_ calling sgp_clear() is still clearing the frame buffer. I'd like to just play with some effects like turning off the clear so that draws accumulate in the buffer, which I thought was possible by no calling clear(), but it's still clearing. Is there some other function I should not be calling? Or is it part of the default sokol_gfx pass action?

**Comment by edubart** [comment]
> Or is it part of the default sokol_gfx pass action?
That is correct, when you call `sg_begin_default_pass()` with default values, it will clear by default. You have to customize its parameters, check Sokol documentation or examples how to disable auto clear on it.
