### ISSUE TITLE
sokol_gp doesn't work with newest sokol

### ISSUE THREAD

**Issue by nateupstairs** [edubart/sokol_gp#32]
sokol did the semi-significant update in May that included a lot of changes to gfx, storage buffers, etc.

with some hacking around, you can definitely make it compile pretty easily (especially just swapping the GLCORE enum), but i think custom shaders would be a bigger lift (though i haven't dug in very seriously).

is there an effort to update this underway? or would you welcome a PR for the delta?

**Comment by nateupstairs** [comment]
totally understood, thanks for the update, i can always pin an older sokol

**Comment by edubart** [comment]
It should now work with newest Sokol in the latest tag I made.
