### ISSUE TITLE
non-vendored sokol (version?)

### ISSUE THREAD

**Issue by konsumer** [edubart/sokol_gp#41]
I get this error:

```
/Users/konsumer/Desktop/otherdev/null0-sokol/build/_deps/sokol_gp-src/sokol_gp.h:1583:10: error: no member named 'fs' in 'struct sg_shader_desc'
 1583 |     desc.fs.images[0].used = true;
```

and a bunch of others that look like the APIs don't match.

I think it is due to a mismatch of API for latest sokol from GitHub. What commit/tag should I target?

I am trying to build everything pulling sokol & sokol_gp from GitHub zips, so I don't have to vendor them. Here is my cmake:

```cmake
FetchContent_Declare(sokol
  URL https://github.com/floooh/sokol/archive/refs/heads/master.zip
)
FetchContent_MakeAvailable(sokol)
include_directories(${sokol_SOURCE_DIR})

FetchContent_Declare(sokol_gp
  URL https://github.com/edubart/sokol_gp/archive/refs/heads/master.zip
)
FetchContent_MakeAvailable(sokol_gp)
include_directories(${sokol_gp_SOURCE_DIR})

add_executable(${PROJECT_NAME} src/main.c)

if(CMAKE_SYSTEM_NAME STREQUAL Darwin)
    target_compile_options(${PROJECT_NAME} PRIVATE -x objective-c)
    target_link_libraries(${PROJECT_NAME}
        "-framework QuartzCore"
        "-framework Cocoa"
        "-framework MetalKit"
        "-framework Metal"
        "-framework OpenGL"
        "-framework AudioToolbox")
else()
    if (CMAKE_SYSTEM_NAME STREQUAL Linux)
        target_link_libraries(${PROJECT_NAME} INTERFACE X11 Xi Xcursor GL asound dl m)
        target_link_libraries(${PROJECT_NAME} PUBLIC Threads::Threads)
    endif()
endif()
```

Here are all the missing members, if an update of sokol_gp makes more sense:

```
sg_shader_desc.fs
sg_shader_desc.vs
sg_shader_vertex_attr.name
sg_shader_vertex_attr.sem_name
sg_shader_vertex_attr.sem_index
```

**Comment by konsumer** [comment]
Essentially, I want a `Findsokol.cmake` that looks something like this (with the version changed on sokol, so they match.)

[Findsokol.cmake.zip](https://github.com/user-attachments/files/17782533/Findsokol.cmake.zip)

**Comment by konsumer** [comment]
If not updating is preferred, I can actually resolve with 

```cmake
FetchContent_Declare(sokol
  URL https://github.com/floooh/sokol/archive/refs/tags/pre-bindings-cleanup.zip
)
```
which is a tag from last month.

**Comment by ekliot** [comment]
@konsumer as a heads up, if you're still dealing with this, sokol gfx had breaking API changes documented [here](https://floooh.github.io/2024/11/04/sokol-fall-2024-update.html) in early Nov.

I haven't yet updated my sokol version to the latest, so I haven't had a chance to investigate a fix for `sokol_gp` to work with those changes, but as a stopgap you could checkout a version of sokol prior to those breaking changes

**Comment by edubart** [comment]
I always recommend using `sokol_gfx.h` bundled in this repository so everything works fine, Sokol sometimes makes breaking changes in the API, and that can make `sokol_gp.h` not work properly. You can always backtrack which `sokol_gfx.h` version your application requires by using same `sokol_gfx.h` published at the date the file https://github.com/edubart/sokol_gp/blob/master/thirdparty/sokol_gfx.h was committed.

In any case, I have updated `sokol_gp.h` to work with the latest `sokol_gfx.h` today, so I expect this issue to be solved.
