### ISSUE TITLE
sample-primitive example don't show points grid

### ISSUE THREAD

**Issue by jorgeluismireles** [edubart/sokol_gp#42]
In Ubuntu sample-primitives compilation don't show the points at the lower left quadrant.

[static void draw_points(void)](https://github.com/edubart/sokol_gp/blob/master/samples/sample-primitives.c#L50C1-L50C32)

![Screenshot from 2024-11-18 10-42-12](https://github.com/user-attachments/assets/50d61c58-0024-4675-ada3-524eb10c7e9b)

**Comment by edubart** [comment]
I confirm that this started happening for me on GL/GLES backends, but not on D3D11, will investigate eventually. I suspect is due to recent changes in Sokol GFX.

**Comment by edubart** [comment]
Fixed this in https://github.com/edubart/sokol_gp/commit/adbe393550ab2874981698a6499589c12632ba54
